language: python

python:
- '3.6'

addons:
    firefox: latest

dist: xenial
services:
    - xvfb

services:
- postgresql

before_install:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver
    - export DISPLAY=:10

install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install -r test-requirements.txt

before_script:
- psql -c 'create database mercury;' -U postgres
- python manage.py migrate
- python manage.py collectstatic --noinput

script:
- black --check --exclude "migrations/" mysite mercury
- flake8 --exclude tests mysite/ mercury/
- flake8 --ignore=E501 mercury/tests/
- coverage run --source=mysite,mercury --omit="mercury/migrations/*" manage.py test

after_script:
- coveralls
- cat geckodriver.log
