# Generated by Django 2.2.10 on 2020-02-27 23:34

import annoying.fields
from django.db import migrations
import json


class Migration(migrations.Migration):

    dependencies = [
        ("mercury", "0009_auto_20200227_2322"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="data",
            field=annoying.fields.JSONField(
                blank=True, deserializer=json.loads, serializer=annoying.fields.dumps
            ),
        ),
    ]
