# Generated by Django 2.2.10 on 2020-02-27 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mercury", "0010_sensordata_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata",
            name="custom_sensor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mercury.CustomSensor"
            ),
        ),
    ]
