# Generated by Django 2.2.10 on 2020-03-01 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0012_auto_20200228_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsensor',
            name='fields',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.
                                    CASCADE, to='mercury.SensorFields'),
        ),
    ]
